---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: environments
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/reshnm/openmcp-deployment
  ref:
    branch: airgapped
  secretRef:
    name: git
