apiVersion: landscaper.services.openmcp.cloud/v1alpha2
kind: ProviderConfig
metadata:
  name: default
  labels:
    landscaper.services.openmcp.cloud/providertype: default
spec:
  deployment:
    repository: europe-docker.pkg.dev/sap-gcp-cp-k8s-stable-hub/landscaper
    availableVersions:
      - v0.136.0
